# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=x86_64-unknown-linux-gnu --run-pass=machine-cse %s -o - | FileCheck %s
#
# Verify that MachineCSE's PerformTrivialCopyPropagation does NOT propagate
# through a FREEZE instruction.
#
# PerformTrivialCopyPropagation, for each use operand of an instruction, checks
# whether the defining instruction is a COPY (isCopy()). FREEZE is not a COPY,
# so users of a frozen value are NOT rewritten to use the pre-freeze source
# directly. This preserves the freeze guarantee: all uses of the frozen value
# see the same fixed value, even when the source is IMPLICIT_DEF.
#
# Contrast: with a plain COPY (freeze_copy_propagates function), the COPY
# source IS propagated into the ADD, collapsing the COPY away.

---
# freeze_blocks_copy_prop: FREEZE is opaque -- ADD keeps using %1 (frozen), not %0 (raw undef).
name:            freeze_blocks_copy_prop
tracksRegLiveness: true
registers:
  - { id: 0, class: gr32 }
  - { id: 1, class: gr32 }
  - { id: 2, class: gr32 }
body:             |
  bb.0:
    ; CHECK-LABEL: name: freeze_blocks_copy_prop
    ; CHECK: [[DEF:%[0-9]+]]:gr32 = IMPLICIT_DEF
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:gr32 = FREEZE [[DEF]]
    ; CHECK-NEXT: [[ADD32rr:%[0-9]+]]:gr32 = ADD32rr [[FREEZE]], [[FREEZE]], implicit-def $eflags
    ; CHECK-NEXT: $eax = COPY [[ADD32rr]]
    ; CHECK-NEXT: RET 0, implicit $eax
    %0:gr32 = IMPLICIT_DEF
    %1:gr32 = FREEZE %0
    %2:gr32 = ADD32rr %1, %1, implicit-def $eflags
    $eax = COPY %2
    RET 0, implicit $eax
...

---
# freeze_copy_propagates: plain COPY IS propagated -- ADD is rewritten to use %0 directly.
name:            freeze_copy_propagates
tracksRegLiveness: true
registers:
  - { id: 0, class: gr32 }
  - { id: 1, class: gr32 }
  - { id: 2, class: gr32 }
body:             |
  bb.0:
    ; CHECK-LABEL: name: freeze_copy_propagates
    ; CHECK: [[DEF:%[0-9]+]]:gr32 = IMPLICIT_DEF
    ; CHECK-NEXT: [[ADD32rr:%[0-9]+]]:gr32 = ADD32rr [[DEF]], [[DEF]], implicit-def $eflags
    ; CHECK-NEXT: $eax = COPY [[ADD32rr]]
    ; CHECK-NEXT: RET 0, implicit $eax
    %0:gr32 = IMPLICIT_DEF
    %1:gr32 = COPY %0
    %2:gr32 = ADD32rr %1, %1, implicit-def $eflags
    $eax = COPY %2
    RET 0, implicit $eax
...
