; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32-unknown-unknown -verify-machineinstrs < %s | FileCheck %s --check-prefix=ASM
; RUN: llc -mtriple=wasm32-unknown-unknown -verify-machineinstrs --stop-after=finalize-isel < %s -o - | FileCheck %s --check-prefix=ISEL
; RUN: llc -mtriple=wasm32-unknown-unknown -verify-machineinstrs --stop-after=postrapseudos < %s -o - | FileCheck %s --check-prefix=POSTRA

define i32 @freeze_i32_multiuse(i32 %x) {
; ASM-LABEL: freeze_i32_multiuse:
; ASM:         .functype freeze_i32_multiuse (i32) -> (i32)
; ASM-NEXT:  # %bb.0:
; ASM-NEXT:    local.get 0
; ASM-NEXT:    i32.const 1
; ASM-NEXT:    i32.add
; ASM-NEXT:    local.tee 0
; ASM-NEXT:    local.get 0
; ASM-NEXT:    i32.add
; ASM-NEXT:    # fallthrough-return
; ISEL-LABEL: name: freeze_i32_multiuse
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $arguments
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
; ISEL-NEXT:   [[FREEZE:%[0-9]+]]:i32 = FREEZE killed [[ARGUMENT_i32_]]
; ISEL-NEXT:   [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 1, implicit-def dead $arguments
; ISEL-NEXT:   [[ADD_I32_:%[0-9]+]]:i32 = ADD_I32 killed [[FREEZE]], killed [[CONST_I32_]], implicit-def dead $arguments
; ISEL-NEXT:   [[ADD_I32_1:%[0-9]+]]:i32 = ADD_I32 [[ADD_I32_]], [[ADD_I32_]], implicit-def dead $arguments
; ISEL-NEXT:   RETURN killed [[ADD_I32_1]], implicit-def dead $arguments
;
; POSTRA-LABEL: name: freeze_i32_multiuse
; POSTRA: bb.0 (%ir-block.0):
; POSTRA-NEXT:   liveins: $arguments
; POSTRA-NEXT: {{  $}}
; POSTRA-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
; POSTRA-NEXT:   [[COPY_I32_:%[0-9]+]]:i32 = COPY_I32 [[ARGUMENT_i32_]], implicit-def $arguments
; POSTRA-NEXT:   [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 1, implicit-def dead $arguments
; POSTRA-NEXT:   [[ADD_I32_:%[0-9]+]]:i32 = ADD_I32 [[COPY_I32_]], [[CONST_I32_]], implicit-def dead $arguments
; POSTRA-NEXT:   [[ADD_I32_1:%[0-9]+]]:i32 = ADD_I32 [[ADD_I32_]], [[ADD_I32_]], implicit-def dead $arguments
; POSTRA-NEXT:   RETURN [[ADD_I32_1]], implicit-def dead $arguments
  %raw = add i32 %x, 1
  %f = freeze i32 %raw
  %sum = add i32 %f, %f
  ret i32 %sum
}

define i32 @freeze_i32_undef() {
; ASM-LABEL: freeze_i32_undef:
; ASM:         .functype freeze_i32_undef () -> (i32)
; ASM-NEXT:  # %bb.0:
; ASM-NEXT:    i32.const 0
; ASM-NEXT:    # fallthrough-return
; ISEL-LABEL: name: freeze_i32_undef
; ISEL: bb.0 (%ir-block.0):
; ISEL-NEXT:   liveins: $arguments
; ISEL-NEXT: {{  $}}
; ISEL-NEXT:   [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 0, implicit-def dead $arguments
; ISEL-NEXT:   RETURN killed [[CONST_I32_]], implicit-def dead $arguments
;
; POSTRA-LABEL: name: freeze_i32_undef
; POSTRA: bb.0 (%ir-block.0):
; POSTRA-NEXT:   liveins: $arguments
; POSTRA-NEXT: {{  $}}
; POSTRA-NEXT:   [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 0, implicit-def dead $arguments
; POSTRA-NEXT:   RETURN [[CONST_I32_]], implicit-def dead $arguments
  %f = freeze i32 undef
  ret i32 %f
}
