; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Fold the div_ceil idiom:
;   zext(add nuw(udiv(A, C), zext(icmp ne(urem(A, C), 0))))
;     -> udiv(zext(A) + C-1, C)   [in the wider type]
; This is the form emitted by Rust for unsigned div_ceil.

declare void @use(i32)
declare void @use128(i128)

; Basic case: i32 dividend, divisor 7, result widened to i64.
define i64 @divceil_i32_to_i64(i32 %x) {
; CHECK-LABEL: @divceil_i32_to_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 6
; CHECK-NEXT:    [[RES:%.*]] = udiv i64 [[TMP2]], 7
; CHECK-NEXT:    ret i64 [[RES]]
;
  %d   = udiv i32 %x, 7
  %r   = urem i32 %x, 7
  %cmp = icmp ne i32 %r, 0
  %inc = zext i1 %cmp to i32
  %sum = add nuw nsw i32 %d, %inc
  %res = zext nneg i32 %sum to i64
  ret i64 %res
}

; Commuted: inc on the left of the add.
define i64 @divceil_i32_to_i64_commuted(i32 %x) {
; CHECK-LABEL: @divceil_i32_to_i64_commuted(
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 6
; CHECK-NEXT:    [[RES:%.*]] = udiv i64 [[TMP2]], 7
; CHECK-NEXT:    ret i64 [[RES]]
;
  %d   = udiv i32 %x, 7
  %r   = urem i32 %x, 7
  %cmp = icmp ne i32 %r, 0
  %inc = zext i1 %cmp to i32
  %sum = add nuw nsw i32 %inc, %d
  %res = zext nneg i32 %sum to i64
  ret i64 %res
}

; Negative: udiv has multiple uses: one-use requirement not met, no fold.
define i64 @divceil_no_fold_multiuse(i32 %x) {
; CHECK-LABEL: @divceil_no_fold_multiuse(
; CHECK-NEXT:    [[D:%.*]] = udiv i32 [[X:%.*]], 7
; CHECK-NEXT:    [[R:%.*]] = urem i32 [[X]], 7
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[R]], 0
; CHECK-NEXT:    [[INC:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    [[SUM:%.*]] = add nuw nsw i32 [[D]], [[INC]]
; CHECK-NEXT:    [[RES:%.*]] = zext nneg i32 [[SUM]] to i64
; CHECK-NEXT:    call void @use(i32 [[D]])
; CHECK-NEXT:    ret i64 [[RES]]
;
  %d   = udiv i32 %x, 7
  %r   = urem i32 %x, 7
  %cmp = icmp ne i32 %r, 0
  %inc = zext i1 %cmp to i32
  %sum = add nuw nsw i32 %d, %inc
  %res = zext nneg i32 %sum to i64
  call void @use(i32 %d)
  ret i64 %res
}

; Negative: divisor is 1 when fold requires C > 1.
define i64 @divceil_no_fold_divisor_one(i32 %x) {
; CHECK-LABEL: @divceil_no_fold_divisor_one(
; CHECK-NEXT:    [[RES:%.*]] = zext nneg i32 [[X:%.*]] to i64
; CHECK-NEXT:    ret i64 [[RES]]
;
  %d   = udiv i32 %x, 1
  %r   = urem i32 %x, 1
  %cmp = icmp ne i32 %r, 0
  %inc = zext i1 %cmp to i32
  %sum = add nuw nsw i32 %d, %inc
  %res = zext nneg i32 %sum to i64
  ret i64 %res
}
