; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Fold: fcmp eq/ne (fadd (fmul X, C1), C2), 0.0 --> fcmp eq/ne X, -C2/C1
; Valid without fast-math flags when C1 is a power of 2, because:
; (1) In IEEE 754, (a + b == 0) iff (a == -b) exactly.
; (2) Multiplication by a power of 2 is exact and injective.

; Basic case: (x * 2.0 - 1.0) == 0.0  -->  x == 0.5
define i1 @fcmp_oeq_fmul2_fadd_neg1(float %x) {
; CHECK-LABEL: @fcmp_oeq_fmul2_fadd_neg1(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[X:%.*]], 5.000000e-01
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float %x, 2.000000e+00
  %add = fadd float %mul, -1.000000e+00
  %cmp = fcmp oeq float %add, 0.000000e+00
  ret i1 %cmp
}

; Same with 'one' predicate.
define i1 @fcmp_one_fmul2_fadd_neg1(float %x) {
; CHECK-LABEL: @fcmp_one_fmul2_fadd_neg1(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp one float [[X:%.*]], 5.000000e-01
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float %x, 2.000000e+00
  %add = fadd float %mul, -1.000000e+00
  %cmp = fcmp one float %add, 0.000000e+00
  ret i1 %cmp
}

; Commuted fmul operands: (2.0 * x - 1.0) == 0.0
define i1 @fcmp_oeq_fmul2_commuted(float %x) {
; CHECK-LABEL: @fcmp_oeq_fmul2_commuted(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[X:%.*]], 5.000000e-01
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float 2.000000e+00, %x
  %add = fadd float %mul, -1.000000e+00
  %cmp = fcmp oeq float %add, 0.000000e+00
  ret i1 %cmp
}

; Commuted fadd operands: (-1.0 + x*2.0) == 0.0
define i1 @fcmp_oeq_fadd_commuted(float %x) {
; CHECK-LABEL: @fcmp_oeq_fadd_commuted(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[X:%.*]], 5.000000e-01
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float %x, 2.000000e+00
  %add = fadd float -1.000000e+00, %mul
  %cmp = fcmp oeq float %add, 0.000000e+00
  ret i1 %cmp
}

; C1 = 4.0: (x * 4.0 - 1.0) == 0.0  -->  x == 0.25
define i1 @fcmp_oeq_fmul4_fadd_neg1(float %x) {
; CHECK-LABEL: @fcmp_oeq_fmul4_fadd_neg1(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[X:%.*]], 2.500000e-01
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float %x, 4.000000e+00
  %add = fadd float %mul, -1.000000e+00
  %cmp = fcmp oeq float %add, 0.000000e+00
  ret i1 %cmp
}

; C1 = 0.5: (x * 0.5 - 1.0) == 0.0  -->  x == 2.0
define i1 @fcmp_oeq_fmul_half_fadd_neg1(float %x) {
; CHECK-LABEL: @fcmp_oeq_fmul_half_fadd_neg1(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[X:%.*]], 2.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float %x, 5.000000e-01
  %add = fadd float %mul, -1.000000e+00
  %cmp = fcmp oeq float %add, 0.000000e+00
  ret i1 %cmp
}

; Double precision.
define i1 @fcmp_oeq_fmul2_fadd_neg1_double(double %x) {
; CHECK-LABEL: @fcmp_oeq_fmul2_fadd_neg1_double(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq double [[X:%.*]], 5.000000e-01
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul double %x, 2.000000e+00
  %add = fadd double %mul, -1.000000e+00
  %cmp = fcmp oeq double %add, 0.000000e+00
  ret i1 %cmp
}

; Motivating benchmark pattern: extract from vector and compare.
define i1 @benchmark_pattern(<2 x float> %arg0) {
; CHECK-LABEL: @benchmark_pattern(
; CHECK-NEXT:    [[V0:%.*]] = extractelement <2 x float> [[ARG0:%.*]], i64 0
; CHECK-NEXT:    [[V2:%.*]] = extractelement <2 x float> [[ARG0]], i64 1
; CHECK-NEXT:    [[V6:%.*]] = fcmp oeq float [[V0]], 5.000000e-01
; CHECK-NEXT:    [[V7:%.*]] = fcmp oeq float [[V2]], 5.000000e-01
; CHECK-NEXT:    [[V8:%.*]] = select i1 [[V6]], i1 [[V7]], i1 false
; CHECK-NEXT:    ret i1 [[V8]]
;
  %v0 = extractelement <2 x float> %arg0, i64 0
  %v1 = fmul float %v0, 2.000000e+00
  %v2 = extractelement <2 x float> %arg0, i64 1
  %v3 = fmul float %v2, 2.000000e+00
  %v4 = fadd float %v1, -1.000000e+00
  %v5 = fadd float %v3, -1.000000e+00
  %v6 = fcmp oeq float %v4, 0.000000e+00
  %v7 = fcmp oeq float %v5, 0.000000e+00
  %v8 = select i1 %v6, i1 %v7, i1 false
  ret i1 %v8
}

; Negative test: C1 = 3.0 is not a power of 2, don't fold.
define i1 @fcmp_oeq_fmul3_fadd_neg1_no_fold(float %x) {
; CHECK-LABEL: @fcmp_oeq_fmul3_fadd_neg1_no_fold(
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[X:%.*]], 3.000000e+00
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[MUL]], -1.000000e+00
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[ADD]], 0.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float %x, 3.000000e+00
  %add = fadd float %mul, -1.000000e+00
  %cmp = fcmp oeq float %add, 0.000000e+00
  ret i1 %cmp
}

; Negative test: RHS is not 0.0, don't fold.
define i1 @fcmp_oeq_fmul2_fadd_neg1_nonzero_rhs(float %x) {
; CHECK-LABEL: @fcmp_oeq_fmul2_fadd_neg1_nonzero_rhs(
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[X:%.*]], 2.000000e+00
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[MUL]], -1.000000e+00
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[ADD]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %mul = fmul float %x, 2.000000e+00
  %add = fadd float %mul, -1.000000e+00
  %cmp = fcmp oeq float %add, 1.000000e+00
  ret i1 %cmp
}
