; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "n64:128"

declare void @use(i8)

; ── Positive cases: lift narrow arithmetic to the wider type ─────────────────

; i8 arithmetic (trunc i32→i8) lifted back to i32, then zext to i64.
define i64 @udiv_i8_to_i64(i32 range(i32 0, 32) %x) {
; CHECK-LABEL: @udiv_i8_to_i64(
; CHECK-NEXT:    [[NARROW:%.*]] = sub nuw nsw i32 38, [[X:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = udiv i32 [[NARROW]], 7
; CHECK-NEXT:    [[D:%.*]] = zext nneg i32 [[TMP1]] to i64
; CHECK-NEXT:    ret i64 [[D]]
;
  %t = trunc nuw nsw i32 %x to i8
  %s = sub nuw nsw i8 38, %t
  %d = udiv i8 %s, 7
  %z = zext i8 %d to i64
  ret i64 %z
}

; i16 arithmetic (trunc i32→i16) lifted back to i32, then zext to i64.
define i64 @udiv_i16_to_i64(i32 range(i32 0, 256) %x) {
; CHECK-LABEL: @udiv_i16_to_i64(
; CHECK-NEXT:    [[NARROW:%.*]] = sub nuw nsw i32 300, [[X:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = udiv i32 [[NARROW]], 13
; CHECK-NEXT:    [[D:%.*]] = zext nneg i32 [[TMP1]] to i64
; CHECK-NEXT:    ret i64 [[D]]
;
  %t = trunc nuw nsw i32 %x to i16
  %s = sub nuw nsw i16 300, %t
  %d = udiv i16 %s, 13
  %z = zext i16 %d to i64
  ret i64 %z
}

; i32 arithmetic (trunc i64→i32) lifted back to i64, zext folds away.
define i64 @udiv_i32_to_i64(i64 range(i64 0, 32) %x) {
; CHECK-LABEL: @udiv_i32_to_i64(
; CHECK-NEXT:    [[S:%.*]] = sub nuw nsw i64 38, [[X:%.*]]
; CHECK-NEXT:    [[D:%.*]] = udiv i64 [[S]], 7
; CHECK-NEXT:    ret i64 [[D]]
;
  %t = trunc nuw nsw i64 %x to i32
  %s = sub nuw nsw i32 38, %t
  %d = udiv i32 %s, 7
  %z = zext i32 %d to i64
  ret i64 %z
}

; i64 arithmetic (trunc i128→i64) lifted back to i128, zext folds away.
define i128 @udiv_i64_to_i128(i128 range(i128 0, 65) %x) {
; CHECK-LABEL: @udiv_i64_to_i128(
; CHECK-NEXT:    [[S:%.*]] = sub nuw nsw i128 70, [[X:%.*]]
; CHECK-NEXT:    [[D:%.*]] = udiv i128 [[S]], 7
; CHECK-NEXT:    ret i128 [[D]]
;
  %t = trunc nuw nsw i128 %x to i64
  %s = sub nuw nsw i64 70, %t
  %d = udiv i64 %s, 7
  %z = zext i64 %d to i128
  ret i128 %z
}

; i32 arithmetic (trunc i128→i32) lifted back to i128, zext folds away.
define i128 @udiv_i32_to_i128(i128 range(i128 0, 35) %x) {
; CHECK-LABEL: @udiv_i32_to_i128(
; CHECK-NEXT:    [[S:%.*]] = sub nuw nsw i128 38, [[X:%.*]]
; CHECK-NEXT:    [[D:%.*]] = udiv i128 [[S]], 7
; CHECK-NEXT:    ret i128 [[D]]
;
  %t = trunc nuw nsw i128 %x to i32
  %s = sub nuw nsw i32 38, %t
  %d = udiv i32 %s, 7
  %z = zext i32 %d to i128
  ret i128 %z
}

; urem also lifts (not just udiv).
define i64 @urem_i8_to_i64(i32 range(i32 0, 32) %x) {
; CHECK-LABEL: @urem_i8_to_i64(
; CHECK-NEXT:    [[NARROW:%.*]] = sub nuw nsw i32 38, [[X:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = urem i32 [[NARROW]], 7
; CHECK-NEXT:    [[R:%.*]] = zext nneg i32 [[TMP1]] to i64
; CHECK-NEXT:    ret i64 [[R]]
;
  %t = trunc nuw nsw i32 %x to i8
  %s = sub nuw nsw i8 38, %t
  %r = urem i8 %s, 7
  %z = zext i8 %r to i64
  ret i64 %z
}

; zext(udiv) where the operand already comes from a zext.
define i64 @udiv_from_zext(i32 range(i32 0, 200) %x) {
; CHECK-LABEL: @udiv_from_zext(
; CHECK-NEXT:    [[TMP1:%.*]] = udiv i32 [[X:%.*]], 7
; CHECK-NEXT:    [[D:%.*]] = zext nneg i32 [[TMP1]] to i64
; CHECK-NEXT:    ret i64 [[D]]
;
  %t = zext i32 %x to i64
  %d = udiv i64 %t, 7
  ret i64 %d
}

; ── Negative cases ────────────────────────────────────────────────────────────

; udiv has multiple uses: can't lift without duplicating.
define i64 @neg_multiuse_udiv(i32 range(i32 0, 32) %x) {
; CHECK-LABEL: @neg_multiuse_udiv(
; CHECK-NEXT:    [[T:%.*]] = trunc nuw nsw i32 [[X:%.*]] to i8
; CHECK-NEXT:    [[S:%.*]] = sub nuw nsw i8 38, [[T]]
; CHECK-NEXT:    [[D:%.*]] = udiv i8 [[S]], 7
; CHECK-NEXT:    call void @use(i8 [[D]])
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i8 [[D]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %t = trunc nuw nsw i32 %x to i8
  %s = sub nuw nsw i8 38, %t
  %d = udiv i8 %s, 7
  call void @use(i8 %d)
  %z = zext i8 %d to i64
  ret i64 %z
}

; The udiv operand is a raw argument (not an instruction): canNotEvaluateInType blocks.
define i64 @neg_arg_operand(i8 %x) {
; CHECK-LABEL: @neg_arg_operand(
; CHECK-NEXT:    [[D:%.*]] = udiv i8 [[X:%.*]], 7
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i8 [[D]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %d = udiv i8 %x, 7
  %z = zext i8 %d to i64
  ret i64 %z
}
