; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mcpu=znver3 -O2 < %s | FileCheck %s
;
; Verify that X86EFlagsReorder + PeepholeOptimizer eliminate redundant TEST/CMP
; instructions when an EFLAGS-producing instruction (TZCNT, LZCNT, POPCNT) is
; separated from its comparison by another EFLAGS-clobbering instruction on a
; different register.
;
; The key case is tzcnt_two_interleaved: without reordering the peephole cannot
; reach TZCNT %x through TZCNT %y, leaving the TEST alive.  The reorder pass
; moves TZCNT %x immediately before TEST %x, and the peephole eliminates the
; TEST and rewrites CMOV NE -> CMOV B (CF=1 means input was zero).

; Simple single-TZCNT case: already handled by the first peephole pass.
; TZCNT sets CF=1 when src==0; CMOV B fires on CF=1, i.e. when x==0.
define i32 @tzcnt_cmov_simple(i32 %x) {
; CHECK-LABEL: tzcnt_cmov_simple:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tzcntl %edi, %eax
; CHECK-NEXT:    cmovbl %edi, %eax
; CHECK-NEXT:    retq
  %tz = tail call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %cmp = icmp eq i32 %x, 0
  %sel = select i1 %cmp, i32 0, i32 %tz
  ret i32 %sel
}

; Simple single-POPCNT case: POPCNT sets ZF=1 when result==0 (i.e. src==0).
; CMOV E fires on ZF=1 (x==0), selecting 0 -- same semantics as the original.
define i32 @popcnt_cmov_simple(i32 %x) {
; CHECK-LABEL: popcnt_cmov_simple:
; CHECK:       # %bb.0:
; CHECK-NEXT:    popcntl %edi, %eax
; CHECK-NEXT:    cmovel %edi, %eax
; CHECK-NEXT:    retq
  %pc = tail call i32 @llvm.ctpop.i32(i32 %x)
  %cmp = icmp eq i32 %x, 0
  %sel = select i1 %cmp, i32 0, i32 %pc
  ret i32 %sel
}

; Two-TZCNT interleaved: TZCNT %y falls between TZCNT %x and TEST %x in the
; natural instruction order, blocking the peephole.  The X86EFlagsReorder pass
; moves TZCNT %x adjacent to TEST %x so the peephole fires.
; Result: no TEST instruction, CMOV B (CF=1 when src==0) instead of CMOV NE.
define i32 @tzcnt_two_interleaved(i32 %x, i32 %y) {
; CHECK-LABEL: tzcnt_two_interleaved:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tzcntl %esi, %ecx
; CHECK-NEXT:    tzcntl %edi, %eax
; CHECK-NEXT:    cmovbl %ecx, %eax
; CHECK-NEXT:    retq
  %tz_x = tail call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %tz_y = tail call i32 @llvm.cttz.i32(i32 %y, i1 true)
  %cmp = icmp eq i32 %x, 0
  ; if x==0, return tz_y; else return tz_x
  %sel = select i1 %cmp, i32 %tz_y, i32 %tz_x
  ret i32 %sel
}

declare i32 @llvm.cttz.i32(i32, i1)
declare i32 @llvm.ctpop.i32(i32)
