; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mcpu=znver3 -O2 < %s | FileCheck %s
;
; Verify compare elimination for direct EFLAGS-producing instruction patterns.
; Also verify we do not reorder across an intervening EFLAGS clobber.

; Simple single-TZCNT case: already handled by the first peephole pass.
; TZCNT sets CF=1 when src==0; CMOV B fires on CF=1, i.e. when x==0.
define i32 @tzcnt_cmov_simple(i32 %x) {
; CHECK-LABEL: tzcnt_cmov_simple:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tzcntl %edi, %eax
; CHECK-NEXT:    cmovbl %edi, %eax
; CHECK-NEXT:    retq
  %tz = tail call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %cmp = icmp eq i32 %x, 0
  %sel = select i1 %cmp, i32 0, i32 %tz
  ret i32 %sel
}

; Simple single-POPCNT case: POPCNT sets ZF=1 when result==0 (i.e. src==0).
; CMOV E fires on ZF=1 (x==0), selecting 0 -- same semantics as the original.
define i32 @popcnt_cmov_simple(i32 %x) {
; CHECK-LABEL: popcnt_cmov_simple:
; CHECK:       # %bb.0:
; CHECK-NEXT:    popcntl %edi, %eax
; CHECK-NEXT:    cmovel %edi, %eax
; CHECK-NEXT:    retq
  %pc = tail call i32 @llvm.ctpop.i32(i32 %x)
  %cmp = icmp eq i32 %x, 0
  %sel = select i1 %cmp, i32 0, i32 %pc
  ret i32 %sel
}

; Two-TZCNT interleaved: the second TZCNT clobbers EFLAGS between TZCNT %x and
; TEST %x. The reorder pass must not move TZCNT %x across that clobber, so the
; explicit TEST remains.
define i32 @tzcnt_two_interleaved(i32 %x, i32 %y) {
; CHECK-LABEL: tzcnt_two_interleaved:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tzcntl %edi, %ecx
; CHECK-NEXT:    tzcntl %esi, %eax
; CHECK-NEXT:    testl %edi, %edi
; CHECK-NEXT:    cmovnel %ecx, %eax
; CHECK-NEXT:    retq
  %tz_x = tail call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %tz_y = tail call i32 @llvm.cttz.i32(i32 %y, i1 true)
  %cmp = icmp eq i32 %x, 0
  ; if x==0, return tz_y; else return tz_x
  %sel = select i1 %cmp, i32 %tz_y, i32 %tz_x
  ret i32 %sel
}

declare i32 @llvm.cttz.i32(i32, i1)
declare i32 @llvm.ctpop.i32(i32)
