; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -stop-after=finalize-isel -mtriple=x86_64-unknown < %s 2>&1 | FileCheck %s
define i32 @const() {
  ; CHECK-LABEL: name: const
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   [[MOV32ri:%[0-9]+]]:gr32 = MOV32ri 1
  ; CHECK-NEXT:   $eax = COPY [[MOV32ri]]
  ; CHECK-NEXT:   RET 0, $eax
  %y = freeze i32 1
  ret i32 %y
}

define i32 @fold(i32 %x) {
  ; CHECK-LABEL: name: fold
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $edi
  ; CHECK-NEXT:   $eax = COPY [[COPY]]
  ; CHECK-NEXT:   RET 0, $eax
  %y = freeze i32 %x
  %z = freeze i32 %y
  ret i32 %z
}

; freeze(undef) must fold to a constant (zero) so that all uses of the frozen
; value see the same consistent value. Without this fold, the undef propagates
; through MachineCSE and ProcessImplicitDefs, giving each use an independent
; IMPLICIT_DEF which the register allocator can assign to different physical
; registers — miscompiling the function. (https://github.com/llvm/llvm-project/issues/58321)
define i32 @freeze_poison(i32 %0) {
  ; CHECK-LABEL: name: freeze_poison
  ; CHECK: bb.0 (%ir-block.1):
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   $eax = COPY [[MOV32r0_]]
  ; CHECK-NEXT:   RET 0, $eax
  %2 = ashr i32 %0, 32
  %3 = freeze i32 %2
  %4 = ashr i32 %3, 3
  %5 = mul i32 %3, %4
  ret i32 %5
}
