; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=i686-- -mattr=+lzcnt | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64--gnux32 -mattr=+lzcnt | FileCheck %s --check-prefix=X32
; RUN: llc < %s -mtriple=x86_64-- -mattr=+lzcnt | FileCheck %s --check-prefix=X64
; RUN: llc < %s -mtriple=x86_64--gnux32 | FileCheck %s --check-prefix=X32-NOLZCNT
; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s --check-prefix=X64-NOLZCNT

declare i8 @llvm.ctlz.i8(i8, i1) nounwind readnone
declare i16 @llvm.ctlz.i16(i16, i1) nounwind readnone
declare i32 @llvm.ctlz.i32(i32, i1) nounwind readnone
declare i64 @llvm.ctlz.i64(i64, i1) nounwind readnone
declare i128 @llvm.ctlz.i128(i128, i1) nounwind readnone

define i8 @t1(i8 %x) nounwind  {
; X86-LABEL: t1:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    lzcntl %eax, %eax
; X86-NEXT:    addl $-24, %eax
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X32-LABEL: t1:
; X32:       # %bb.0:
; X32-NEXT:    movzbl %dil, %eax
; X32-NEXT:    lzcntl %eax, %eax
; X32-NEXT:    addl $-24, %eax
; X32-NEXT:    # kill: def $al killed $al killed $eax
; X32-NEXT:    retq
;
; X64-LABEL: t1:
; X64:       # %bb.0:
; X64-NEXT:    movzbl %dil, %eax
; X64-NEXT:    lzcntl %eax, %eax
; X64-NEXT:    addl $-24, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t1:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movzbl %dil, %ecx
; X32-NOLZCNT-NEXT:    movl $15, %eax
; X32-NOLZCNT-NEXT:    bsrl %ecx, %eax
; X32-NOLZCNT-NEXT:    xorl $7, %eax
; X32-NOLZCNT-NEXT:    # kill: def $al killed $al killed $eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t1:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movzbl %dil, %ecx
; X64-NOLZCNT-NEXT:    movl $15, %eax
; X64-NOLZCNT-NEXT:    bsrl %ecx, %eax
; X64-NOLZCNT-NEXT:    xorl $7, %eax
; X64-NOLZCNT-NEXT:    # kill: def $al killed $al killed $eax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i8 @llvm.ctlz.i8( i8 %x, i1 false )
	ret i8 %tmp
}

define i16 @t2(i16 %x) nounwind  {
; X86-LABEL: t2:
; X86:       # %bb.0:
; X86-NEXT:    lzcntw {{[0-9]+}}(%esp), %ax
; X86-NEXT:    retl
;
; X32-LABEL: t2:
; X32:       # %bb.0:
; X32-NEXT:    lzcntw %di, %ax
; X32-NEXT:    retq
;
; X64-LABEL: t2:
; X64:       # %bb.0:
; X64-NEXT:    lzcntw %di, %ax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t2:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movw $31, %ax
; X32-NOLZCNT-NEXT:    bsrw %di, %ax
; X32-NOLZCNT-NEXT:    xorl $15, %eax
; X32-NOLZCNT-NEXT:    # kill: def $ax killed $ax killed $eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t2:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movw $31, %ax
; X64-NOLZCNT-NEXT:    bsrw %di, %ax
; X64-NOLZCNT-NEXT:    xorl $15, %eax
; X64-NOLZCNT-NEXT:    # kill: def $ax killed $ax killed $eax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i16 @llvm.ctlz.i16( i16 %x, i1 false )
	ret i16 %tmp
}

define i32 @t3(i32 %x) nounwind  {
; X86-LABEL: t3:
; X86:       # %bb.0:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    retl
;
; X32-LABEL: t3:
; X32:       # %bb.0:
; X32-NEXT:    lzcntl %edi, %eax
; X32-NEXT:    retq
;
; X64-LABEL: t3:
; X64:       # %bb.0:
; X64-NEXT:    lzcntl %edi, %eax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t3:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movl $63, %eax
; X32-NOLZCNT-NEXT:    bsrl %edi, %eax
; X32-NOLZCNT-NEXT:    xorl $31, %eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t3:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movl $63, %eax
; X64-NOLZCNT-NEXT:    bsrl %edi, %eax
; X64-NOLZCNT-NEXT:    xorl $31, %eax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i32 @llvm.ctlz.i32( i32 %x, i1 false )
	ret i32 %tmp
}

define i64 @t4(i64 %x) nounwind  {
; X86-LABEL: t4:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    jne .LBB3_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    retl
; X86-NEXT:  .LBB3_1:
; X86-NEXT:    lzcntl %eax, %eax
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    retl
;
; X32-LABEL: t4:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rdi, %rax
; X32-NEXT:    retq
;
; X64-LABEL: t4:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rdi, %rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t4:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movl $127, %eax
; X32-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X32-NOLZCNT-NEXT:    xorq $63, %rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t4:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movl $127, %eax
; X64-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X64-NOLZCNT-NEXT:    xorq $63, %rax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i64 @llvm.ctlz.i64( i64 %x, i1 false )
	ret i64 %tmp
}

define i8 @t5(i8 %x) nounwind  {
; X86-LABEL: t5:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shll $24, %eax
; X86-NEXT:    lzcntl %eax, %eax
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X32-LABEL: t5:
; X32:       # %bb.0:
; X32-NEXT:    shll $24, %edi
; X32-NEXT:    lzcntl %edi, %eax
; X32-NEXT:    # kill: def $al killed $al killed $eax
; X32-NEXT:    retq
;
; X64-LABEL: t5:
; X64:       # %bb.0:
; X64-NEXT:    shll $24, %edi
; X64-NEXT:    lzcntl %edi, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t5:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movzbl %dil, %eax
; X32-NOLZCNT-NEXT:    bsrl %eax, %eax
; X32-NOLZCNT-NEXT:    xorl $7, %eax
; X32-NOLZCNT-NEXT:    # kill: def $al killed $al killed $eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t5:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movzbl %dil, %eax
; X64-NOLZCNT-NEXT:    bsrl %eax, %eax
; X64-NOLZCNT-NEXT:    xorl $7, %eax
; X64-NOLZCNT-NEXT:    # kill: def $al killed $al killed $eax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i8 @llvm.ctlz.i8( i8 %x, i1 true )
	ret i8 %tmp
}

define i16 @t6(i16 %x) nounwind  {
; X86-LABEL: t6:
; X86:       # %bb.0:
; X86-NEXT:    lzcntw {{[0-9]+}}(%esp), %ax
; X86-NEXT:    retl
;
; X32-LABEL: t6:
; X32:       # %bb.0:
; X32-NEXT:    lzcntw %di, %ax
; X32-NEXT:    retq
;
; X64-LABEL: t6:
; X64:       # %bb.0:
; X64-NEXT:    lzcntw %di, %ax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t6:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    bsrw %di, %ax
; X32-NOLZCNT-NEXT:    xorl $15, %eax
; X32-NOLZCNT-NEXT:    # kill: def $ax killed $ax killed $eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t6:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    bsrw %di, %ax
; X64-NOLZCNT-NEXT:    xorl $15, %eax
; X64-NOLZCNT-NEXT:    # kill: def $ax killed $ax killed $eax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i16 @llvm.ctlz.i16( i16 %x, i1 true )
	ret i16 %tmp
}

define i32 @t7(i32 %x) nounwind  {
; X86-LABEL: t7:
; X86:       # %bb.0:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    retl
;
; X32-LABEL: t7:
; X32:       # %bb.0:
; X32-NEXT:    lzcntl %edi, %eax
; X32-NEXT:    retq
;
; X64-LABEL: t7:
; X64:       # %bb.0:
; X64-NEXT:    lzcntl %edi, %eax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t7:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    bsrl %edi, %eax
; X32-NOLZCNT-NEXT:    xorl $31, %eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t7:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    bsrl %edi, %eax
; X64-NOLZCNT-NEXT:    xorl $31, %eax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i32 @llvm.ctlz.i32( i32 %x, i1 true )
	ret i32 %tmp
}

define i64 @t8(i64 %x) nounwind  {
; X86-LABEL: t8:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    jne .LBB7_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    retl
; X86-NEXT:  .LBB7_1:
; X86-NEXT:    lzcntl %eax, %eax
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    retl
;
; X32-LABEL: t8:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rdi, %rax
; X32-NEXT:    retq
;
; X64-LABEL: t8:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rdi, %rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: t8:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X32-NOLZCNT-NEXT:    xorq $63, %rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: t8:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X64-NOLZCNT-NEXT:    xorq $63, %rax
; X64-NOLZCNT-NEXT:    retq
	%tmp = tail call i64 @llvm.ctlz.i64( i64 %x, i1 true )
	ret i64 %tmp
}

; Verify that i128 ctlz uses LZCNT's CF output to avoid a redundant TEST.
; The high half is computed last. CMOVB selects based on CF directly.
; Note: X86 (32-bit) splits the i128 into 4 i32 chunks and cannot use the
; CF->CMOV optimization; it emits branches as expected.
define i64 @lzcnt128(ptr %p) nounwind {
; X86-LABEL: lzcnt128:
; X86:       # %bb.0:
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    movl 4(%esi), %edi
; X86-NEXT:    movl 8(%esi), %ecx
; X86-NEXT:    movl 12(%esi), %edx
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    jne .LBB8_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl %ecx, %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    je .LBB8_5
; X86-NEXT:  .LBB8_4:
; X86-NEXT:    lzcntl %edi, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    je .LBB8_7
; X86-NEXT:    jmp .LBB8_8
; X86-NEXT:  .LBB8_1:
; X86-NEXT:    lzcntl %edx, %eax
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB8_4
; X86-NEXT:  .LBB8_5:
; X86-NEXT:    lzcntl (%esi), %esi
; X86-NEXT:    addl $32, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    jne .LBB8_8
; X86-NEXT:  .LBB8_7:
; X86-NEXT:    addl $64, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB8_8:
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    retl
;
; X32-LABEL: lzcnt128:
; X32:       # %bb.0:
; X32-NEXT:    movq 8(%edi), %rcx
; X32-NEXT:    lzcntq %rcx, %rdx
; X32-NEXT:    lzcntq (%edi), %rax
; X32-NEXT:    addq $64, %rax
; X32-NEXT:    testq %rcx, %rcx
; X32-NEXT:    cmovneq %rdx, %rax
; X32-NEXT:    retq
;
; X64-LABEL: lzcnt128:
; X64:       # %bb.0:
; X64-NEXT:    movq 8(%rdi), %rcx
; X64-NEXT:    lzcntq %rcx, %rdx
; X64-NEXT:    lzcntq (%rdi), %rax
; X64-NEXT:    addq $64, %rax
; X64-NEXT:    testq %rcx, %rcx
; X64-NEXT:    cmovneq %rdx, %rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: lzcnt128:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movq 8(%edi), %rcx
; X32-NOLZCNT-NEXT:    bsrq %rcx, %rdx
; X32-NOLZCNT-NEXT:    xorq $63, %rdx
; X32-NOLZCNT-NEXT:    bsrq (%edi), %rax
; X32-NOLZCNT-NEXT:    xorq $63, %rax
; X32-NOLZCNT-NEXT:    orq $64, %rax
; X32-NOLZCNT-NEXT:    testq %rcx, %rcx
; X32-NOLZCNT-NEXT:    cmovneq %rdx, %rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: lzcnt128:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movq 8(%rdi), %rcx
; X64-NOLZCNT-NEXT:    bsrq %rcx, %rdx
; X64-NOLZCNT-NEXT:    xorq $63, %rdx
; X64-NOLZCNT-NEXT:    bsrq (%rdi), %rax
; X64-NOLZCNT-NEXT:    xorq $63, %rax
; X64-NOLZCNT-NEXT:    orq $64, %rax
; X64-NOLZCNT-NEXT:    testq %rcx, %rcx
; X64-NOLZCNT-NEXT:    cmovneq %rdx, %rax
; X64-NOLZCNT-NEXT:    retq
  %a = load i128, ptr %p, align 8
  %cnt = tail call i128 @llvm.ctlz.i128(i128 %a, i1 true)
  %res = trunc i128 %cnt to i64
  ret i64 %res
}

; Without LZCNT the optimization isn't possible, so verify BSR is emitted with
; an explicit testq and that cmovbq isn't emitted.
define i64 @lzcnt128_no_lzcnt(ptr %p) nounwind {
; X86-LABEL: lzcnt128_no_lzcnt:
; X86:       # %bb.0:
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    movl 4(%esi), %edi
; X86-NEXT:    movl 8(%esi), %ecx
; X86-NEXT:    movl 12(%esi), %edx
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    jne .LBB9_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl %ecx, %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    je .LBB9_5
; X86-NEXT:  .LBB9_4:
; X86-NEXT:    lzcntl %edi, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    je .LBB9_7
; X86-NEXT:    jmp .LBB9_8
; X86-NEXT:  .LBB9_1:
; X86-NEXT:    lzcntl %edx, %eax
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB9_4
; X86-NEXT:  .LBB9_5:
; X86-NEXT:    lzcntl (%esi), %esi
; X86-NEXT:    addl $32, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    jne .LBB9_8
; X86-NEXT:  .LBB9_7:
; X86-NEXT:    addl $64, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB9_8:
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    retl
;
; X32-LABEL: lzcnt128_no_lzcnt:
; X32:       # %bb.0:
; X32-NEXT:    movq 8(%edi), %rcx
; X32-NEXT:    lzcntq %rcx, %rdx
; X32-NEXT:    lzcntq (%edi), %rax
; X32-NEXT:    addq $64, %rax
; X32-NEXT:    testq %rcx, %rcx
; X32-NEXT:    cmovneq %rdx, %rax
; X32-NEXT:    retq
;
; X64-LABEL: lzcnt128_no_lzcnt:
; X64:       # %bb.0:
; X64-NEXT:    movq 8(%rdi), %rcx
; X64-NEXT:    lzcntq %rcx, %rdx
; X64-NEXT:    lzcntq (%rdi), %rax
; X64-NEXT:    addq $64, %rax
; X64-NEXT:    testq %rcx, %rcx
; X64-NEXT:    cmovneq %rdx, %rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: lzcnt128_no_lzcnt:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movq 8(%edi), %rcx
; X32-NOLZCNT-NEXT:    bsrq %rcx, %rdx
; X32-NOLZCNT-NEXT:    xorq $63, %rdx
; X32-NOLZCNT-NEXT:    bsrq (%edi), %rax
; X32-NOLZCNT-NEXT:    xorq $63, %rax
; X32-NOLZCNT-NEXT:    orq $64, %rax
; X32-NOLZCNT-NEXT:    testq %rcx, %rcx
; X32-NOLZCNT-NEXT:    cmovneq %rdx, %rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: lzcnt128_no_lzcnt:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movq 8(%rdi), %rcx
; X64-NOLZCNT-NEXT:    bsrq %rcx, %rdx
; X64-NOLZCNT-NEXT:    xorq $63, %rdx
; X64-NOLZCNT-NEXT:    bsrq (%rdi), %rax
; X64-NOLZCNT-NEXT:    xorq $63, %rax
; X64-NOLZCNT-NEXT:    orq $64, %rax
; X64-NOLZCNT-NEXT:    testq %rcx, %rcx
; X64-NOLZCNT-NEXT:    cmovneq %rdx, %rax
; X64-NOLZCNT-NEXT:    retq
  %a = load i128, ptr %p, align 8
  %cnt = tail call i128 @llvm.ctlz.i128(i128 %a, i1 true)
  %res = trunc i128 %cnt to i64
  ret i64 %res
}

define i32 @clz_i128_issue32709_swap(i64 %x_lo, i64 %x_hi) {
; X86-LABEL: clz_i128_issue32709_swap:
; X86:       # %bb.0:
; X86-NEXT:    pushl %edi
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    pushl %esi
; X86-NEXT:    .cfi_def_cfa_offset 12
; X86-NEXT:    .cfi_offset %esi, -12
; X86-NEXT:    .cfi_offset %edi, -8
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    jne .LBB10_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl %edx, %ecx
; X86-NEXT:    addl $32, %ecx
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    je .LBB10_5
; X86-NEXT:  .LBB10_4:
; X86-NEXT:    lzcntl %eax, %edi
; X86-NEXT:    jmp .LBB10_6
; X86-NEXT:  .LBB10_1:
; X86-NEXT:    lzcntl %esi, %ecx
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    jne .LBB10_4
; X86-NEXT:  .LBB10_5:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %edi
; X86-NEXT:    addl $32, %edi
; X86-NEXT:  .LBB10_6:
; X86-NEXT:    xorl %eax, %eax
; X86-NEXT:    orl %esi, %edx
; X86-NEXT:    jne .LBB10_8
; X86-NEXT:  # %bb.7:
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:  .LBB10_8:
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    popl %esi
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    popl %edi
; X86-NEXT:    .cfi_def_cfa_offset 4
; X86-NEXT:    retl
;
; X32-LABEL: clz_i128_issue32709_swap:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rdi, %rax
; X32-NEXT:    lzcntq %rsi, %rcx
; X32-NEXT:    xorl %edx, %edx
; X32-NEXT:    testq %rdi, %rdi
; X32-NEXT:    cmovnel %edx, %ecx
; X32-NEXT:    addl %ecx, %eax
; X32-NEXT:    # kill: def $eax killed $eax killed $rax
; X32-NEXT:    retq
;
; X64-LABEL: clz_i128_issue32709_swap:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rdi, %rax
; X64-NEXT:    lzcntq %rsi, %rcx
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    testq %rdi, %rdi
; X64-NEXT:    cmovnel %edx, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    # kill: def $eax killed $eax killed $rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: clz_i128_issue32709_swap:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movl $127, %ecx
; X32-NOLZCNT-NEXT:    movl $127, %edx
; X32-NOLZCNT-NEXT:    bsrq %rdi, %rdx
; X32-NOLZCNT-NEXT:    xorl $63, %edx
; X32-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X32-NOLZCNT-NEXT:    xorl $63, %ecx
; X32-NOLZCNT-NEXT:    xorl %eax, %eax
; X32-NOLZCNT-NEXT:    testq %rdi, %rdi
; X32-NOLZCNT-NEXT:    cmovel %ecx, %eax
; X32-NOLZCNT-NEXT:    addl %edx, %eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: clz_i128_issue32709_swap:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movl $127, %ecx
; X64-NOLZCNT-NEXT:    movl $127, %edx
; X64-NOLZCNT-NEXT:    bsrq %rdi, %rdx
; X64-NOLZCNT-NEXT:    xorl $63, %edx
; X64-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X64-NOLZCNT-NEXT:    xorl $63, %ecx
; X64-NOLZCNT-NEXT:    xorl %eax, %eax
; X64-NOLZCNT-NEXT:    testq %rdi, %rdi
; X64-NOLZCNT-NEXT:    cmovel %ecx, %eax
; X64-NOLZCNT-NEXT:    addl %edx, %eax
; X64-NOLZCNT-NEXT:    retq
  %a = tail call i64 @llvm.ctlz.i64(i64 %x_lo, i1 false)
  %b = tail call i64 @llvm.ctlz.i64(i64 %x_hi, i1 false)
  %is_nonzero = icmp ne i64 %x_lo, 0
  %sel = select i1 %is_nonzero, i64 0, i64 %b
  %sum = add nuw nsw i64 %sel, %a
  %res = trunc i64 %sum to i32
  ret i32 %res
}

; Same fold via COND_E: CMOV(0, CTLZ(x), E, CMP(x,0)) -> CMOV(CTLZ(x), 0, AE, LZCNT(x).flags)
; The inverted condition (icmp eq instead of ne) produces COND_E; the fold handles both.
define i32 @clz_i128_issue32709_swap_cond_e(i64 %x_lo, i64 %x_hi) {
; X86-LABEL: clz_i128_issue32709_swap_cond_e:
; X86:       # %bb.0:
; X86-NEXT:    pushl %esi
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    .cfi_offset %esi, -8
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    jne .LBB11_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl %edx, %ecx
; X86-NEXT:    addl $32, %ecx
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    je .LBB11_5
; X86-NEXT:  .LBB11_4:
; X86-NEXT:    lzcntl %eax, %eax
; X86-NEXT:    orl %esi, %edx
; X86-NEXT:    jne .LBB11_7
; X86-NEXT:    jmp .LBB11_8
; X86-NEXT:  .LBB11_1:
; X86-NEXT:    lzcntl %esi, %ecx
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    jne .LBB11_4
; X86-NEXT:  .LBB11_5:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    orl %esi, %edx
; X86-NEXT:    je .LBB11_8
; X86-NEXT:  .LBB11_7:
; X86-NEXT:    xorl %eax, %eax
; X86-NEXT:  .LBB11_8:
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    popl %esi
; X86-NEXT:    .cfi_def_cfa_offset 4
; X86-NEXT:    retl
;
; X32-LABEL: clz_i128_issue32709_swap_cond_e:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rdi, %rax
; X32-NEXT:    lzcntq %rsi, %rcx
; X32-NEXT:    xorl %edx, %edx
; X32-NEXT:    testq %rdi, %rdi
; X32-NEXT:    cmovnel %edx, %ecx
; X32-NEXT:    addl %ecx, %eax
; X32-NEXT:    # kill: def $eax killed $eax killed $rax
; X32-NEXT:    retq
;
; X64-LABEL: clz_i128_issue32709_swap_cond_e:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rdi, %rax
; X64-NEXT:    lzcntq %rsi, %rcx
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    testq %rdi, %rdi
; X64-NEXT:    cmovnel %edx, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    # kill: def $eax killed $eax killed $rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: clz_i128_issue32709_swap_cond_e:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movl $127, %ecx
; X32-NOLZCNT-NEXT:    movl $127, %edx
; X32-NOLZCNT-NEXT:    bsrq %rdi, %rdx
; X32-NOLZCNT-NEXT:    xorl $63, %edx
; X32-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X32-NOLZCNT-NEXT:    xorl $63, %ecx
; X32-NOLZCNT-NEXT:    xorl %eax, %eax
; X32-NOLZCNT-NEXT:    testq %rdi, %rdi
; X32-NOLZCNT-NEXT:    cmovel %ecx, %eax
; X32-NOLZCNT-NEXT:    addl %edx, %eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: clz_i128_issue32709_swap_cond_e:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movl $127, %ecx
; X64-NOLZCNT-NEXT:    movl $127, %edx
; X64-NOLZCNT-NEXT:    bsrq %rdi, %rdx
; X64-NOLZCNT-NEXT:    xorl $63, %edx
; X64-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X64-NOLZCNT-NEXT:    xorl $63, %ecx
; X64-NOLZCNT-NEXT:    xorl %eax, %eax
; X64-NOLZCNT-NEXT:    testq %rdi, %rdi
; X64-NOLZCNT-NEXT:    cmovel %ecx, %eax
; X64-NOLZCNT-NEXT:    addl %edx, %eax
; X64-NOLZCNT-NEXT:    retq
  %a = tail call i64 @llvm.ctlz.i64(i64 %x_lo, i1 false)
  %b = tail call i64 @llvm.ctlz.i64(i64 %x_hi, i1 false)
  %is_zero = icmp eq i64 %x_lo, 0
  %sel = select i1 %is_zero, i64 %b, i64 0
  %sum = add nuw nsw i64 %sel, %a
  %res = trunc i64 %sum to i32
  ret i32 %res
}

; Verify that i128 ctlz on a register arg (i1 true) uses LZCNT's CF to avoid
; a redundant TEST. Emitted by ExpandIntRes_CTLZ for register-based i128.
; Note: X86 (32-bit) splits i128 into 4 i32 chunks and uses branches.
define i32 @lzcnt128_reg_true(i128 %x) nounwind {
; X86-LABEL: lzcnt128_reg_true:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $16, %esp
; X86-NEXT:    movl 12(%ebp), %esi
; X86-NEXT:    movl 16(%ebp), %ecx
; X86-NEXT:    movl 20(%ebp), %edx
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    jne .LBB12_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl %ecx, %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    je .LBB12_5
; X86-NEXT:  .LBB12_4:
; X86-NEXT:    lzcntl %esi, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    je .LBB12_7
; X86-NEXT:    jmp .LBB12_8
; X86-NEXT:  .LBB12_1:
; X86-NEXT:    lzcntl %edx, %eax
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    jne .LBB12_4
; X86-NEXT:  .LBB12_5:
; X86-NEXT:    lzcntl 8(%ebp), %esi
; X86-NEXT:    addl $32, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    jne .LBB12_8
; X86-NEXT:  .LBB12_7:
; X86-NEXT:    addl $64, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB12_8:
; X86-NEXT:    leal -4(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl
;
; X32-LABEL: lzcnt128_reg_true:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rsi, %rcx
; X32-NEXT:    lzcntq %rdi, %rax
; X32-NEXT:    addl $64, %eax
; X32-NEXT:    testq %rsi, %rsi
; X32-NEXT:    cmovnel %ecx, %eax
; X32-NEXT:    # kill: def $eax killed $eax killed $rax
; X32-NEXT:    retq
;
; X64-LABEL: lzcnt128_reg_true:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rsi, %rcx
; X64-NEXT:    lzcntq %rdi, %rax
; X64-NEXT:    addl $64, %eax
; X64-NEXT:    testq %rsi, %rsi
; X64-NEXT:    cmovnel %ecx, %eax
; X64-NEXT:    # kill: def $eax killed $eax killed $rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: lzcnt128_reg_true:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X32-NOLZCNT-NEXT:    xorl $63, %ecx
; X32-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X32-NOLZCNT-NEXT:    xorl $63, %eax
; X32-NOLZCNT-NEXT:    orl $64, %eax
; X32-NOLZCNT-NEXT:    testq %rsi, %rsi
; X32-NOLZCNT-NEXT:    cmovnel %ecx, %eax
; X32-NOLZCNT-NEXT:    # kill: def $eax killed $eax killed $rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: lzcnt128_reg_true:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X64-NOLZCNT-NEXT:    xorl $63, %ecx
; X64-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X64-NOLZCNT-NEXT:    xorl $63, %eax
; X64-NOLZCNT-NEXT:    orl $64, %eax
; X64-NOLZCNT-NEXT:    testq %rsi, %rsi
; X64-NOLZCNT-NEXT:    cmovnel %ecx, %eax
; X64-NOLZCNT-NEXT:    # kill: def $eax killed $eax killed $rax
; X64-NOLZCNT-NEXT:    retq
  %cnt = tail call i128 @llvm.ctlz.i128(i128 %x, i1 true)
  %res = trunc i128 %cnt to i32
  ret i32 %res
}

; Verify that i128 ctlz on a register arg (i1 false, Rust u128::leading_zeros)
; also uses LZCNT's CF to avoid a redundant TEST.
define i32 @lzcnt128_reg_false(i128 %x) nounwind {
; X86-LABEL: lzcnt128_reg_false:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $16, %esp
; X86-NEXT:    movl 12(%ebp), %esi
; X86-NEXT:    movl 16(%ebp), %ecx
; X86-NEXT:    movl 20(%ebp), %edx
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    jne .LBB13_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl %ecx, %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    je .LBB13_5
; X86-NEXT:  .LBB13_4:
; X86-NEXT:    lzcntl %esi, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    je .LBB13_7
; X86-NEXT:    jmp .LBB13_8
; X86-NEXT:  .LBB13_1:
; X86-NEXT:    lzcntl %edx, %eax
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    jne .LBB13_4
; X86-NEXT:  .LBB13_5:
; X86-NEXT:    lzcntl 8(%ebp), %esi
; X86-NEXT:    addl $32, %esi
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    jne .LBB13_8
; X86-NEXT:  .LBB13_7:
; X86-NEXT:    addl $64, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB13_8:
; X86-NEXT:    leal -4(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl
;
; X32-LABEL: lzcnt128_reg_false:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rsi, %rcx
; X32-NEXT:    lzcntq %rdi, %rax
; X32-NEXT:    addl $64, %eax
; X32-NEXT:    testq %rsi, %rsi
; X32-NEXT:    cmovnel %ecx, %eax
; X32-NEXT:    # kill: def $eax killed $eax killed $rax
; X32-NEXT:    retq
;
; X64-LABEL: lzcnt128_reg_false:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rsi, %rcx
; X64-NEXT:    lzcntq %rdi, %rax
; X64-NEXT:    addl $64, %eax
; X64-NEXT:    testq %rsi, %rsi
; X64-NEXT:    cmovnel %ecx, %eax
; X64-NEXT:    # kill: def $eax killed $eax killed $rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: lzcnt128_reg_false:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X32-NOLZCNT-NEXT:    xorl $63, %ecx
; X32-NOLZCNT-NEXT:    movl $127, %eax
; X32-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X32-NOLZCNT-NEXT:    xorl $63, %eax
; X32-NOLZCNT-NEXT:    addl $64, %eax
; X32-NOLZCNT-NEXT:    testq %rsi, %rsi
; X32-NOLZCNT-NEXT:    cmovnel %ecx, %eax
; X32-NOLZCNT-NEXT:    # kill: def $eax killed $eax killed $rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: lzcnt128_reg_false:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X64-NOLZCNT-NEXT:    xorl $63, %ecx
; X64-NOLZCNT-NEXT:    movl $127, %eax
; X64-NOLZCNT-NEXT:    bsrq %rdi, %rax
; X64-NOLZCNT-NEXT:    xorl $63, %eax
; X64-NOLZCNT-NEXT:    addl $64, %eax
; X64-NOLZCNT-NEXT:    testq %rsi, %rsi
; X64-NOLZCNT-NEXT:    cmovnel %ecx, %eax
; X64-NOLZCNT-NEXT:    # kill: def $eax killed $eax killed $rax
; X64-NOLZCNT-NEXT:    retq
  %cnt = tail call i128 @llvm.ctlz.i128(i128 %x, i1 false)
  %res = trunc i128 %cnt to i32
  ret i32 %res
}

; Negative tests: verify the fold does NOT fire when correctness can't be guaranteed.

; Pattern 2 guard: IfArm's CTLZ operates on lo, but CmpSrc is hi.
; Using LZCNT(hi).CF to select between CTLZ(lo) values would return LZCNT(hi)
; instead of CTLZ(lo) when hi is nonzero - wrong result.
define i32 @no_fold_wrong_ctlz_src(i64 %lo, i64 %hi) {
; X86-LABEL: no_fold_wrong_ctlz_src:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    jne .LBB14_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    addl $32, %eax
; X86-NEXT:    orl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    je .LBB14_4
; X86-NEXT:    jmp .LBB14_5
; X86-NEXT:  .LBB14_1:
; X86-NEXT:    lzcntl %eax, %eax
; X86-NEXT:    orl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    jne .LBB14_5
; X86-NEXT:  .LBB14_4:
; X86-NEXT:    addl $64, %eax
; X86-NEXT:  .LBB14_5:
; X86-NEXT:    retl
;
; X32-LABEL: no_fold_wrong_ctlz_src:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rdi, %rcx
; X32-NEXT:    leal 64(%rcx), %eax
; X32-NEXT:    testq %rsi, %rsi
; X32-NEXT:    cmovnel %ecx, %eax
; X32-NEXT:    retq
;
; X64-LABEL: no_fold_wrong_ctlz_src:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rdi, %rcx
; X64-NEXT:    leal 64(%rcx), %eax
; X64-NEXT:    testq %rsi, %rsi
; X64-NEXT:    cmovnel %ecx, %eax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: no_fold_wrong_ctlz_src:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movl $127, %ecx
; X32-NOLZCNT-NEXT:    bsrq %rdi, %rcx
; X32-NOLZCNT-NEXT:    xorl $63, %ecx
; X32-NOLZCNT-NEXT:    leal 64(%rcx), %eax
; X32-NOLZCNT-NEXT:    testq %rsi, %rsi
; X32-NOLZCNT-NEXT:    cmovnel %ecx, %eax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: no_fold_wrong_ctlz_src:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movl $127, %ecx
; X64-NOLZCNT-NEXT:    bsrq %rdi, %rcx
; X64-NOLZCNT-NEXT:    xorl $63, %ecx
; X64-NOLZCNT-NEXT:    leal 64(%rcx), %eax
; X64-NOLZCNT-NEXT:    testq %rsi, %rsi
; X64-NOLZCNT-NEXT:    cmovnel %ecx, %eax
; X64-NOLZCNT-NEXT:    retq
  %a = tail call i64 @llvm.ctlz.i64(i64 %lo, i1 false)
  %b = add i64 %a, 64
  %cmp = icmp ne i64 %hi, 0
  %sel = select i1 %cmp, i64 %a, i64 %b
  %res = trunc i64 %sel to i32
  ret i32 %res
}

; Pattern 1 guard: IfArm is 1, not 0 - the zero-arm pattern requires IfArm == 0.
define i64 @no_fold_nonzero_if_arm(i64 %lo, i64 %hi) {
; X86-LABEL: no_fold_nonzero_if_arm:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    testl %ecx, %ecx
; X86-NEXT:    jne .LBB15_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    lzcntl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    addl $32, %ecx
; X86-NEXT:    jmp .LBB15_3
; X86-NEXT:  .LBB15_1:
; X86-NEXT:    lzcntl %ecx, %ecx
; X86-NEXT:  .LBB15_3:
; X86-NEXT:    orl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl $1, %eax
; X86-NEXT:    jne .LBB15_5
; X86-NEXT:  # %bb.4:
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:  .LBB15_5:
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    retl
;
; X32-LABEL: no_fold_nonzero_if_arm:
; X32:       # %bb.0:
; X32-NEXT:    lzcntq %rsi, %rcx
; X32-NEXT:    testq %rdi, %rdi
; X32-NEXT:    movl $1, %eax
; X32-NEXT:    cmoveq %rcx, %rax
; X32-NEXT:    retq
;
; X64-LABEL: no_fold_nonzero_if_arm:
; X64:       # %bb.0:
; X64-NEXT:    lzcntq %rsi, %rcx
; X64-NEXT:    testq %rdi, %rdi
; X64-NEXT:    movl $1, %eax
; X64-NEXT:    cmoveq %rcx, %rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: no_fold_nonzero_if_arm:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    movl $127, %ecx
; X32-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X32-NOLZCNT-NEXT:    xorq $63, %rcx
; X32-NOLZCNT-NEXT:    testq %rdi, %rdi
; X32-NOLZCNT-NEXT:    movl $1, %eax
; X32-NOLZCNT-NEXT:    cmoveq %rcx, %rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: no_fold_nonzero_if_arm:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    movl $127, %ecx
; X64-NOLZCNT-NEXT:    bsrq %rsi, %rcx
; X64-NOLZCNT-NEXT:    xorq $63, %rcx
; X64-NOLZCNT-NEXT:    testq %rdi, %rdi
; X64-NOLZCNT-NEXT:    movl $1, %eax
; X64-NOLZCNT-NEXT:    cmoveq %rcx, %rax
; X64-NOLZCNT-NEXT:    retq
  %b = tail call i64 @llvm.ctlz.i64(i64 %hi, i1 false)
  %cmp = icmp ne i64 %lo, 0
  %sel = select i1 %cmp, i64 1, i64 %b
  ret i64 %sel
}

; Pattern 1 guard: ElseArm is not ctlz-like - no CF to reuse.
define i64 @no_fold_else_not_ctlz(i64 %lo, i64 %hi) {
; X86-LABEL: no_fold_else_not_ctlz:
; X86:       # %bb.0:
; X86-NEXT:    pushl %esi
; X86-NEXT:    .cfi_def_cfa_offset 8
; X86-NEXT:    .cfi_offset %esi, -8
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    addl $5, %ecx
; X86-NEXT:    adcl $0, %esi
; X86-NEXT:    xorl %eax, %eax
; X86-NEXT:    orl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    jne .LBB16_2
; X86-NEXT:  # %bb.1:
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    movl %esi, %edx
; X86-NEXT:  .LBB16_2:
; X86-NEXT:    popl %esi
; X86-NEXT:    .cfi_def_cfa_offset 4
; X86-NEXT:    retl
;
; X32-LABEL: no_fold_else_not_ctlz:
; X32:       # %bb.0:
; X32-NEXT:    leaq 5(%rsi), %rcx
; X32-NEXT:    xorl %eax, %eax
; X32-NEXT:    testq %rdi, %rdi
; X32-NEXT:    cmoveq %rcx, %rax
; X32-NEXT:    retq
;
; X64-LABEL: no_fold_else_not_ctlz:
; X64:       # %bb.0:
; X64-NEXT:    leaq 5(%rsi), %rcx
; X64-NEXT:    xorl %eax, %eax
; X64-NEXT:    testq %rdi, %rdi
; X64-NEXT:    cmoveq %rcx, %rax
; X64-NEXT:    retq
;
; X32-NOLZCNT-LABEL: no_fold_else_not_ctlz:
; X32-NOLZCNT:       # %bb.0:
; X32-NOLZCNT-NEXT:    leaq 5(%rsi), %rcx
; X32-NOLZCNT-NEXT:    xorl %eax, %eax
; X32-NOLZCNT-NEXT:    testq %rdi, %rdi
; X32-NOLZCNT-NEXT:    cmoveq %rcx, %rax
; X32-NOLZCNT-NEXT:    retq
;
; X64-NOLZCNT-LABEL: no_fold_else_not_ctlz:
; X64-NOLZCNT:       # %bb.0:
; X64-NOLZCNT-NEXT:    leaq 5(%rsi), %rcx
; X64-NOLZCNT-NEXT:    xorl %eax, %eax
; X64-NOLZCNT-NEXT:    testq %rdi, %rdi
; X64-NOLZCNT-NEXT:    cmoveq %rcx, %rax
; X64-NOLZCNT-NEXT:    retq
  %inc = add i64 %hi, 5
  %cmp = icmp ne i64 %lo, 0
  %sel = select i1 %cmp, i64 0, i64 %inc
  ret i64 %sel
}
