; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s --check-prefixes=CHECK,CHECK-NOBMI2
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mcpu=haswell | FileCheck %s --check-prefixes=CHECK,CHECK-BMI2

define i64 @mulx64(i64 %x) {
; CHECK-NOBMI2-LABEL: mulx64:
; CHECK-NOBMI2:       # %bb.0: # %entry
; CHECK-NOBMI2-NEXT:    movabsq $-7046029254386353131, %rax # imm = 0x9E3779B97F4A7C15
; CHECK-NOBMI2-NEXT:    mulq %rdi
; CHECK-NOBMI2-NEXT:    xorq %rdx, %rax
; CHECK-NOBMI2-NEXT:    retq
;
; CHECK-BMI2-LABEL: mulx64:
; CHECK-BMI2:       # %bb.0: # %entry
; CHECK-BMI2-NEXT:    movabsq $-7046029254386353131, %rdx # imm = 0x9E3779B97F4A7C15
; CHECK-BMI2-NEXT:    mulxq %rdi, %rax, %rcx
; CHECK-BMI2-NEXT:    xorq %rcx, %rax
; CHECK-BMI2-NEXT:    retq
entry:
  %x.zext = zext i64 %x to i128
  %mul = mul nuw i128 %x.zext, 11400714819323198485
  %hi = lshr i128 %mul, 64
  %mix = xor i128 %mul, %hi
  %ret = trunc i128 %mix to i64
  ret i64 %ret
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
