; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -O2 -mtriple=x86_64-pc-linux-gnu < %s | FileCheck %s --check-prefix=X64
; RUN: llc -O2 -mtriple=i686-pc-linux-gnu   < %s | FileCheck %s --check-prefix=X86
;
; High half of 32-bit widening multiply.
; On x86-64, the zext+mul i64+lshr 32 pattern should lower to mull/imull
; (implicit %edx:%eax form) rather than imulq+shrq.
; On 32-bit x86, this already works correctly.

; ---------------------------------------------------------------------------
; Unsigned: (uint64_t)a * b >> 32
; ---------------------------------------------------------------------------

define i32 @mul_hi_u32(i32 %a, i32 %b) {
; X64-LABEL: mul_hi_u32:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    mull %esi
; X64-NEXT:    movl %edx, %eax
; X64-NEXT:    retq
;
; X86-LABEL: mul_hi_u32:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    mull {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    retl
  %a64  = zext i32 %a to i64
  %b64  = zext i32 %b to i64
  %prod = mul i64 %a64, %b64
  %hi   = lshr i64 %prod, 32
  %r    = trunc i64 %hi to i32
  ret i32 %r
}

; ---------------------------------------------------------------------------
; Signed: (int64_t)a * b >> 32
; ---------------------------------------------------------------------------

define i32 @mul_hi_s32(i32 %a, i32 %b) {
; X64-LABEL: mul_hi_s32:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    imull %esi
; X64-NEXT:    movl %edx, %eax
; X64-NEXT:    retq
;
; X86-LABEL: mul_hi_s32:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    imull {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    retl
  %a64  = sext i32 %a to i64
  %b64  = sext i32 %b to i64
  %prod = mul nsw i64 %a64, %b64
  %hi   = ashr i64 %prod, 32
  %r    = trunc i64 %hi to i32
  ret i32 %r
}

; ---------------------------------------------------------------------------
; With constant: (int64_t)a * 0xABCD >> 32
; ---------------------------------------------------------------------------

define i32 @mul_hi_s32_const(i32 %a) {
; X64-LABEL: mul_hi_s32_const:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    movl $43981, %ecx
; X64-NEXT:    imull %ecx
; X64-NEXT:    movl %edx, %eax
; X64-NEXT:    retq
;
; X86-LABEL: mul_hi_s32_const:
; X86:       # %bb.0:
; X86-NEXT:    movl $43981, %eax
; X86-NEXT:    imull {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    retl
  %a64  = sext i32 %a to i64
  %prod = mul nsw i64 %a64, 43981
  %hi   = ashr i64 %prod, 32
  %r    = trunc i64 %hi to i32
  ret i32 %r
}

; ---------------------------------------------------------------------------
; With constant: (uint64_t)a * 0xABCD >> 32
; ---------------------------------------------------------------------------

define i32 @mul_hi_u32_const(i32 %a) {
; X64-LABEL: mul_hi_u32_const:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    movl $43981, %ecx
; X64-NEXT:    mull %ecx
; X64-NEXT:    movl %edx, %eax
; X64-NEXT:    retq
;
; X86-LABEL: mul_hi_u32_const:
; X86:       # %bb.0:
; X86-NEXT:    movl $43981, %eax
; X86-NEXT:    mull {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    retl
  %a64  = zext i32 %a to i64
  %prod = mul i64 %a64, 43981
  %hi   = lshr i64 %prod, 32
  %r    = trunc i64 %hi to i32
  ret i32 %r
}
